# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20171121_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagroup',
            name='downloaded_at',
            field=models.DateTimeField(),
        ),
    ]
