# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_datadocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadocument',
            name='product_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
