# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20171130_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadocument',
            name='product_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
